package io.dimasan.riseandshine.core;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class QuoteGenerator {

    private Random randomGenerator;
    private List<String> rises;
    private List<String> shines;

    public QuoteGenerator() {
        randomGenerator = new Random();
        rises = new ArrayList<>();
        shines = new ArrayList<>();

        rises.add("Взойди");
        rises.add("Взыграй духом");
        rises.add("Воспрянь");
        rises.add("Восстань");
        rises.add("Вскочи");
        rises.add("Вспрянь");
        rises.add("Вспыхни");
        rises.add("Встань");
        rises.add("Встань на ноги");
        rises.add("Выйди из-за горизонта");
        rises.add("Вырвись из объятий Морфея");
        rises.add("Наполнись жизнью");
        rises.add("Обмогнись");
        rises.add("Обновись");
        rises.add("Образумься");
        rises.add("Образумься");
        rises.add("Одумайся");
        rises.add("Оживись");
        rises.add("Оклемайся");
        rises.add("Окрепни");
        rises.add("Опамятуйся");
        rises.add("Опомнись");
        rises.add("Оправься");
        rises.add("Очнись ото сна");
        rises.add("Очувствуйся");
        rises.add("Очухайся");
        rises.add("Повысся");
        rises.add("Подбодрись");
        rises.add("Подними голову");
        rises.add("Поднимись над горизонтом");
        rises.add("Поднимись");
        rises.add("Подорвись");
        rises.add("Подымись");
        rises.add("Прийди в себя");
        rises.add("Прийди в сознание");
        rises.add("Прийди в чувство");
        rises.add("Приободрись");
        rises.add("Пробудись");
        rises.add("Продри зенки");
        rises.add("Просейся");
        rises.add("Проснись");
        rises.add("Протри глаза");
        rises.add("Прочухайся");
        rises.add("Расчехлись");
        rises.add("Умножься");
        rises.add("Эрегируй");

        shines.add("авраль");
        shines.add("бди");
        shines.add("бодрствуй");
        shines.add("будь на ходу");
        shines.add("будь у дел");
        shines.add("вези воз");
        shines.add("взаимодействуй");
        shines.add("вкалывай");
        shines.add("впахивай");
        shines.add("выбивайся из сил");
        shines.add("выйди из зоны комфорта");
        shines.add("выжми все что можно");
        shines.add("гегемонь");
        shines.add("гни горб");
        shines.add("гни хребтину");
        shines.add("гни хрип");
        shines.add("гни шею");
        shines.add("действуй");
        shines.add("делай своё");
        shines.add("займись делом");
        shines.add("занимайся");
        shines.add("засучи рукава");
        shines.add("ишачь");
        shines.add("копти");
        shines.add("корпи");
        shines.add("корячься");
        shines.add("корячься");
        shines.add("костоломь");
        shines.add("лижи пятки");
        shines.add("ломай хрип");
        shines.add("маневрируй");
        shines.add("мантуль");
        shines.add("мастери");
        shines.add("мастрачь");
        shines.add("мозолься");
        shines.add("надрывай пуп");
        shines.add("надрывайся");
        shines.add("натирай мозоли");
        shines.add("не покладай рук");
        shines.add("орудуй");
        shines.add("падай ниц");
        shines.add("парься");
        shines.add("паши");
        shines.add("паши как лошадь");
        shines.add("паши как трактор");
        shines.add("плыви против течения");
        shines.add("ползай на брюхе");
        shines.add("ползай ужом");
        shines.add("потей над чем-то");
        shines.add("пресмыкайся");
        shines.add("проливай пот");
        shines.add("пыхти");
        shines.add("работай без разгибу");
        shines.add("работай без устали");
        shines.add("работай в поте лица");
        shines.add("работай до седьмого пота");
        shines.add("работай за троих");
        shines.add("работай как вол");
        shines.add("работай как каторжный");
        shines.add("работай как лошадь");
        shines.add("работай как проклятый");
        shines.add("работай на износ");
        shines.add("работай не разгибая спины");
        shines.add("работай сутками");
        shines.add("работай");
        shines.add("рви жилы");
        shines.add("рви пупок");
        shines.add("рубись");
        shines.add("сгибайся в три дуги");
        shines.add("совершай работу");
        shines.add("сооружай");
        shines.add("спины не разгибай");
        shines.add("труби");
        shines.add("трудись");
        shines.add("тяни лямку");
        shines.add("умывайся потом");
        shines.add("функциклируй");
        shines.add("функционируй");
        shines.add("фурычь");
        shines.add("чертоломь");
        shines.add("шабашничай");
        shines.add("шакаль");
        shines.add("шуруй");
    }

    public String getRandomQuote() {
        int index = randomGenerator.nextInt(rises.size());
        StringBuilder sb = new StringBuilder();
        sb.append(" — ");
        sb.append(rises.get(index));
        sb.append(" и ");
        index = randomGenerator.nextInt(shines.size());
        sb.append(shines.get(index));
        sb.append("!");
        return sb.toString();
    }
}
